"""Minimum-viable LoFTR fine-tuning experiment.

Fine-tunes ONLY the last 3 of LoFTR's 8 coarse self/cross-attention layers
(~2M of the model's ~11M total params) on the synthetic pairs already
generated by the invariance sweep (backend/outputs/invariance_sweep/) --
these have EXACT ground-truth homographies, unlike any real pair in this
project. Freezing everything else preserves the pretrained (outdoor,
natural-image) feature quality while letting only the matching-head-facing
layers adapt to lunar terrain's texture statistics.

Loss: a simplified analog of LoFTR's real coarse-level supervision, not
the full official training loss (that also supervises the fine-level
stage, uses hard-negative-aware focal loss, etc. -- out of scope for a
"minimum viable" experiment). For each pair: run the (partially trainable)
model up through loftr_coarse to get per-cell features for both images,
project each source coarse-grid cell's center through the pair's exact
H_gt to find its true target cell in the reference grid, and apply
cross-entropy between the model's own dense coarse similarity matrix and
that ground-truth target index -- directly supervising the same
representation LoFTR's real coarse matching stage reads from, using real,
non-fabricated correspondence.

Evaluation: run the REAL, unmodified pipeline (run_pipeline.run_registration)
on the actual Tycho NAC pair via matching.py's normal code path, before and
after swapping in the fine-tuned weights -- not a separate simplified eval,
the same pipeline every other result in this project went through.
"""
from __future__ import annotations

import glob
import json
import os
import random
import time

import cv2
import numpy as np
import torch
import torch.nn.functional as F

VARIANTS_DIR = "backend/outputs/invariance_sweep/variants"
CHECKPOINT_PATH = "backend/outputs/loftr_lunar_finetuned.pt"
MAX_SIDE = 320          # small, CPU-feasible working resolution
NUM_STEPS = 150         # bounded, real step count -- not a fabricated "it ran forever"
LR = 1e-5


def load_training_pairs() -> list[dict]:
    """Every synthetic pair with a non-trivial (non-identity) ground-truth
    transform -- the identity cases carry no useful gradient signal."""
    pairs = []
    for gt_path in glob.glob(os.path.join(VARIANTS_DIR, "*", "*__groundtruth.json")):
        with open(gt_path) as f:
            meta = json.load(f)
        H = np.array(meta["H_gt"])
        if np.allclose(H, np.eye(3), atol=1e-6):
            continue
        base = gt_path.replace("__groundtruth.json", "")
        src_path, ref_path = base + "__src.png", base + "__ref.png"
        if not (os.path.exists(src_path) and os.path.exists(ref_path)):
            continue
        pairs.append({"src": src_path, "ref": ref_path, "H_gt": H})
    return pairs


def prep_image(path: str):
    """Loads + resizes to MAX_SIDE. Caller adjusts H_gt for the resulting
    per-image scale factor separately (see main())."""
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    h, w = img.shape
    scale = MAX_SIDE / max(h, w)
    resized = cv2.resize(img, (max(1, int(w * scale)), max(1, int(h * scale))))
    t = torch.from_numpy(resized).float()[None, None] / 255.0
    return t, scale, resized.shape


def build_target_indices(H_gt_resized: np.ndarray, hw0_c: tuple, hw1_c: tuple) -> torch.Tensor:
    """For each coarse cell (1/8-resolution grid) in image0, projects its
    center through H_gt to find the true target cell in image1's coarse
    grid. Returns a (N0,) long tensor of target flat indices into image1's
    (h1*w1) grid, with -100 (ignored by cross_entropy) for cells whose true
    target falls outside image1's bounds."""
    h0c, w0c = hw0_c
    h1c, w1c = hw1_c
    ys, xs = np.meshgrid(np.arange(h0c), np.arange(w0c), indexing="ij")
    # coarse-cell center -> full-resolution pixel coords (x8, +4 for cell center)
    px = (xs.ravel() * 8 + 4).astype(np.float64)
    py = (ys.ravel() * 8 + 4).astype(np.float64)
    pts = np.stack([px, py, np.ones_like(px)], axis=0)
    proj = H_gt_resized @ pts
    proj = proj[:2] / proj[2]
    tx, ty = proj[0] / 8.0, proj[1] / 8.0  # back to coarse-grid units in image1
    tx_i, ty_i = np.round(tx).astype(int), np.round(ty).astype(int)
    valid = (tx_i >= 0) & (tx_i < w1c) & (ty_i >= 0) & (ty_i < h1c)
    target = np.full(h0c * w0c, -100, dtype=np.int64)
    flat_idx = ty_i * w1c + tx_i
    target[valid] = flat_idx[valid]
    return torch.from_numpy(target)


def coarse_forward(model, img_t):
    """Backbone + positional encoding, up to (but not including) loftr_coarse
    -- returned separately so the caller can run loftr_coarse with gradients
    enabled only for its own trainable layers."""
    feat_c, _feat_f = model.backbone(img_t)
    hw_c = feat_c.shape[2:]
    feat_c = model.pos_encoding(feat_c).permute(0, 2, 3, 1)
    n, h, w, c = feat_c.shape
    return feat_c.reshape(n, -1, c), hw_c


def main():
    import kornia.feature as KF

    print("[finetune] loading pretrained LoFTR (outdoor)...")
    model = KF.LoFTR(pretrained="outdoor")
    model.train()

    for p in model.parameters():
        p.requires_grad = False
    trainable_layers = model.loftr_coarse.layers[-3:]
    for layer in trainable_layers:
        for p in layer.parameters():
            p.requires_grad = True
    trainable_params = [p for p in model.parameters() if p.requires_grad]
    n_trainable = sum(p.numel() for p in trainable_params)
    n_total = sum(p.numel() for p in model.parameters())
    print(f"[finetune] trainable: {n_trainable:,} / {n_total:,} params "
          f"(last {len(trainable_layers)} of {len(model.loftr_coarse.layers)} coarse transformer layers)")

    pairs = load_training_pairs()
    print(f"[finetune] {len(pairs)} non-trivial synthetic ground-truth pairs available")

    optimizer = torch.optim.Adam(trainable_params, lr=LR)

    rng = random.Random(0)
    losses = []
    t0 = time.time()
    for step in range(NUM_STEPS):
        pair = rng.choice(pairs)
        src_t, src_scale, src_shape = prep_image(pair["src"])
        ref_t, ref_scale, ref_shape = prep_image(pair["ref"])

        # Adjust H_gt for independent resizing of src/ref to MAX_SIDE.
        # H_gt maps ORIGINAL src px -> ORIGINAL ref px. We need RESIZED src
        # px -> RESIZED ref px: resized_src = S_src @ orig_src, so
        # orig_src = S_src^-1 @ resized_src; orig_ref = H_gt @ orig_src;
        # resized_ref = S_ref @ orig_ref. Compose: S_ref @ H_gt @ S_src^-1.
        S_ref = np.diag([ref_scale, ref_scale, 1.0])
        S_src_inv = np.diag([1 / src_scale, 1 / src_scale, 1.0])
        H_resized = S_ref @ pair["H_gt"] @ S_src_inv

        try:
            feat_c0, hw0_c = coarse_forward(model, src_t)
            feat_c1, hw1_c = coarse_forward(model, ref_t)
            feat_c0, feat_c1 = model.loftr_coarse(feat_c0, feat_c1)
        except Exception as e:
            print(f"[finetune] step {step}: skipped ({e})")
            continue

        target = build_target_indices(H_resized, hw0_c, hw1_c)
        n_valid = (target >= 0).sum().item()
        if n_valid < 4:
            continue

        feat_c0n = F.normalize(feat_c0, dim=-1)
        feat_c1n = F.normalize(feat_c1, dim=-1)
        sim = torch.einsum("nlc,nsc->nls", feat_c0n, feat_c1n) / 0.1  # temperature, matches LoFTR's own scale
        loss = F.cross_entropy(sim[0], target, ignore_index=-100)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        losses.append(loss.item())
        if step % 10 == 0 or step == NUM_STEPS - 1:
            recent = losses[-10:]
            print(f"[finetune] step {step}/{NUM_STEPS} loss={loss.item():.4f} "
                  f"(mean last {len(recent)}: {sum(recent)/len(recent):.4f}) "
                  f"n_valid_cells={n_valid} elapsed={time.time()-t0:.0f}s")

    print(f"[finetune] done: {len(losses)} real gradient steps in {time.time()-t0:.0f}s")
    if losses:
        first10 = sum(losses[:10]) / min(10, len(losses))
        last10 = sum(losses[-10:]) / min(10, len(losses))
        print(f"[finetune] loss trend: first-10 mean={first10:.4f} -> last-10 mean={last10:.4f}")

    os.makedirs(os.path.dirname(CHECKPOINT_PATH), exist_ok=True)
    torch.save(model.state_dict(), CHECKPOINT_PATH)
    print(f"[finetune] saved fine-tuned weights to {CHECKPOINT_PATH}")


if __name__ == "__main__":
    main()
